name: pull request

on:
  pull_request:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: install
      run: npm install

    - name: format
      run: npm run format

#    - name: test
#      run: npm run test

    - name: deploy
      run: npm run deploy-to-s3
      env:
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        
    - name: Add PR Comment
      uses: mshick/add-pr-comment@v1
      if: success()
      with:
        message: "Success"
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Add PR Comment
      uses: mshick/add-pr-comment@v1
      if: failure()
      with:
        message: "Failure"
        repo-token: ${{ secrets.GITHUB_TOKEN }}
